language: php

php:
  - 5.5
  - 5.6

env:
  - ENV=test

before_script:
  - composer self-update
  - composer install --no-interaction

script: phpunit

matrix:
  allow_failures:
    - php: 5.5
    - php: 5.6
  fast_finish: true

notifications:
  on_success: never
  on_failure: always