#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

$app = new Symfony\Component\Console\Application('Homestead - Homestead Config Manager', '0.1.0');

$app->add(new Homesteader\Config\ConfigListCommand);
$app->add(new Homesteader\Config\ConfigShowCommand);
$app->add(new Homesteader\Config\ConfigNewCommand);

$app->run();